export const newsData = [
  {
    id: 1,
    title: "EX-SENATOR URGES NEW YORK DEMS",
    content:
      "Lorem ipsum dolor sit amet consectuier adipiscing elit sedet diames nonumiere nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisine",
    publicationDate: "26-APR-2022",
    author: "SUPER USER",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-12/1281983_3207700_Untitled-17_updates.jpg",
    source: "Politics Daily",
    category: "Politics",
    url: "#",
  },
  {
    id: 2,
    title: "GLOBAL MARKETS SHOW SIGNS OF RECOVERY",
    content:
      "Stock markets rebound as investors regain confidence following economic policy announcements.",
    publicationDate: "12-FEB-2025",
    author: "ECONOMY WATCH",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-13/1282427_5286772_IK-COAS_updates.jpg",
    source: "Business Insider",
    category: "Business",
    url: "#",
  },
  {
    id: 3,
    title: "NEW AI TOOL DETECTS FAKE NEWS WITH 98% ACCURACY",
    content:
      "A breakthrough AI model can now identify misinformation with unprecedented precision.",
    publicationDate: "10-FEB-2025",
    author: "TECH REPORTER",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-13/1282347_3935302_trump_updates.jpg",
    source: "Tech Trends",
    category: "Technology",
    url: "#",
  },
  {
    id: 4,
    title: "CLIMATE CHANGE EFFECTS INTENSIFY IN COASTAL REGIONS",
    content:
      "Rising sea levels and extreme weather conditions pose a growing threat to coastal communities.",
    publicationDate: "09-FEB-2025",
    author: "ENVIRONMENT DESK",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-13/1282377_1789958_Untitled-10_updates.jpg",
    source: "Green Journal",
    category: "Environment",
    url: "#",
  },
  {
    id: 5,
    title: "WORLD LEADERS MEET TO DISCUSS PEACE AGREEMENT",
    content:
      "Diplomats from major nations gather to negotiate an end to ongoing conflicts in the region.",
    publicationDate: "08-FEB-2025",
    author: "GLOBAL AFFAIRS",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-13/1282365_2677757_trump_updates.jpg",
    source: "World News",
    category: "World",
    url: "#",
  },
  {
    id: 6,
    title: "NEW IPHONE RELEASED WITH GROUNDBREAKING FEATURES",
    content:
      "Apple unveils its latest flagship phone, boasting enhanced AI capabilities and a revolutionary camera system.",
    publicationDate: "07-FEB-2025",
    author: "GADGET GURU",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-12/1282057_4550743_Untitled-1_updates.jpg",
    source: "Tech Radar",
    category: "Technology",
    url: "#",
  },
  {
    id: 7,
    title: "LOCAL SPORTS TEAM WINS CHAMPIONSHIP AFTER 10 YEARS",
    content:
      "Fans celebrate as their team secures a historic victory in a nail-biting final match.",
    publicationDate: "06-FEB-2025",
    author: "SPORTS ANALYST",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-12/1282014_2057368_Bangladesh-protest-2_updates.jpg",
    source: "Sports Weekly",
    category: "Sports",
    url: "#",
  },
  {
    id: 8,
    title: "NEW HEALTH STUDY REVEALS SURPRISING BENEFITS OF MEDITATION",
    content:
      "Scientists discover that daily meditation can significantly improve mental and physical health.",
    publicationDate: "05-FEB-2025",
    author: "HEALTH EXPERT",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-12/1282057_4550743_Untitled-1_updates.jpg",
    source: "Medical News",
    category: "Health",
    url: "#",
  },
  {
    id: 9,
    title: "NASA ANNOUNCES NEW MISSION TO EXPLORE DEEP SPACE",
    content:
      "The space agency plans to send an advanced probe beyond our solar system to study interstellar phenomena.",
    publicationDate: "04-FEB-2025",
    author: "SPACE RESEARCHER",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-12/1281965_5888506_ELON-MUSK-SON-34_updates.jpg",
    source: "Space Today",
    category: "Science",
    url: "#",
  },
  {
    id: 10,
    title: "HOLLYWOOD STAR ANNOUNCES RETIREMENT AFTER 30 YEARS",
    content:
      "Fans react to the shocking news as the legendary actor decides to step away from the spotlight.",
    publicationDate: "03-FEB-2025",
    author: "ENTERTAINMENT REPORTER",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-12/1281983_3207700_Untitled-17_updates.jpg",
    source: "Entertainment Daily",
    category: "Entertainment",
    url: "#",
  },
  {
    id: 11,
    title: "NEW STUDY SHOWS RISING INFLATION IMPACTING HOUSEHOLDS",
    content:
      "Experts warn that inflation rates could continue to rise, affecting purchasing power worldwide.",
    publicationDate: "02-FEB-2025",
    author: "ECONOMIC ANALYST",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-12/1281965_5888506_ELON-MUSK-SON-34_updates.jpg",
    source: "Financial Times",
    category: "Economy",
    url: "#",
  },
  {
    id: 12,
    title: "GOVERNMENT ANNOUNCES NEW EDUCATION POLICY REFORMS",
    content:
      "The latest policy changes aim to improve access to quality education and modernize the curriculum.",
    publicationDate: "01-FEB-2025",
    author: "EDUCATION SPECIALIST",
    imageUrl: "https://www.thenews.com.pk/assets/uploads/updates/2025-02-13/1282365_2677757_trump_updates.jpg",
    source: "Education Weekly",
    category: "Education",
    url: "#",
  },
];
